require("halias.plugins-setup")
require("halias.core.options")
require("halias.core.colorscheme")
require("halias.core.keymaps")

require("halias.plugins.nvim-tree")
require("halias.plugins.lualine")
require("halias.plugins.telescope")
require("halias.plugins.nvim-cmp")
require("halias.plugins.lsp.mason")
require("halias.plugins.lsp.lspsaga")
require("halias.plugins.lsp.lspconfig")
require("halias.plugins.lsp.null-ls")
require("halias.plugins.autopairs")
require("halias.plugins.autotag")
require("halias.plugins.treesitter")
require("halias.plugins.leap")
require("halias.plugins.bufferline")
